### ISSUE TITLE
Must press boot and reset button for first flash with bootloader

### ISSUE THREAD

**Issue by twalter23** [owntech-foundation/Core#1]
When flashing a code for the first time with the USB bootloader, reset and boot button must be pressed before clicking "flash" with platformio.

**Comment by jalinei** [comment]
This is more of a documentation issue as it is indeed the expected behaviour.

**Comment by jalinei** [comment]
Now documented here : 
https://owntech-foundation.github.io/Documentation/bootloader/docs/getting_started/
