### ISSUE TITLE
[TwistAPI] eliminate All from function calls to harmonize function naming

### ISSUE THREAD

**Issue by jalinei** [owntech-foundation/Core#44]
**Description**
Functions in the power api are split evenly between All and Leg. This is a potential problem as it is unclear from the function names what is "All".

linked with #35 we need a clever naming to be able to differentiate leg instances. Power is not necessarily linked to a leg, but might be linked to a single switch as well. Therefore `All` in the name is not the only current shortcoming.

**Correction**
Either:
      
Eliminate the All functions and create an equivalent behavior using the Leg functions  
Rename the All functions to AllLegs which makes it more readable

**Comment by luizvilla** [comment]
This is solved by commit 0d01337. 

Now all functions have the `ALL_LEGS` option. I have also suppressed the word `Leg` from the function calls.
