### ISSUE TITLE
[ADC] Problem with adcTriggerSoftwareConversion ? 

### ISSUE THREAD

**Issue by jalinei** [owntech-foundation/Core#45]
hello,

![image](https://github.com/owntech-foundation/Core/assets/22010135/ce8a896a-6014-4f31-a8d6-0b25a1c06356)

I'm trying to read samples in my program. This works 2 times in a row but not 3 or more times. This is what I get 

```plaintext
data 3298.000000
data 3299.000000
data -10000.000000
data -10000.000000
data -10000.000000 
```

Am I doing something wrong?

**Comment by cfoucher-laas** [comment]
PR #17 is ready for testing after I performed additional tests, this should indeed fix this issue.
