### ISSUE TITLE
[platformio.ini] Wrong library version

### ISSUE THREAD

**Issue by luizvilla** [owntech-foundation/Core#63]
**Describe the bug**
The core currently points to the wrong version of the `examples library`.

**To Reproduce**
1. Use the example interface to download the voltage mode example
2. Note it uses `opalib_pid.h`
3. Try to build and it will fail. 

**Expected behavior**
That the core pull the correct version that includes `pid.h`.

**Additional context**
This can be easily solved by updating the `platformio.ini`

**Comment by jalinei** [comment]
Fixed by 95d7aed
